#!/usr/bin/env node
/**
 * Publish a real signal through the real pipeline and print what a subscriber sees.
 *
 * Uses live market data. The rationale is generated by Claude if ANTHROPIC_API_KEY is set,
 * otherwise the deterministic template fires — both paths are shown.
 *
 *   node scripts/feed-sample.mjs
 */

import { OkxPublicClient, snapshotFromCandles } from '@plumb/market';
import { createSeededIdFactory, runCycle } from '@plumb/strategy';
import { DEFAULT_RISK_CONFIG, initialState, evaluate as governorEvaluate } from '@plumb/risk';
import { PERMISSIVE_CONFIG, permissiveStrategy } from '@plumb/backtest';
import {
  FeedStore,
  buildTrackRecord,
  callTool,
  formatSignalForDelivery,
  generateRationale,
  publishThenExecute,
} from '@plumb/asp';

const instId = 'BTC-USDT-SWAP';
const market = new OkxPublicClient();
const store = new FeedStore();

const candles = await market.candles(instId, '1H', { limit: 300 });
const funding = await market.fundingRate(instId);
const now = Date.now();
const snapshot = snapshotFromCandles({
  now,
  instId,
  candles: [{ tf: '1H', ohlcv: candles }],
  fundingRate: funding.fundingRate,
});

const config = { ...PERMISSIVE_CONFIG, trendEma: { ...PERMISSIVE_CONFIG.trendEma, atrMultiple: 6 } };
const cycle = runCycle(snapshot, {
  now,
  newId: createSeededIdFactory(now % 100000),
  config,
  modules: [permissiveStrategy],
  state: { openPositions: [], lastSignalAt: {} },
});

const signal = cycle.signals[0];
if (signal === undefined) {
  console.log(`no signal this cycle (regime ${cycle.regime.label}) — try again shortly`);
  process.exit(0);
}

const verdict = governorEvaluate(
  signal,
  initialState(now),
  { instId, ts: now, degraded: false, degradedFields: [], last: snapshot.last, funding: { current: snapshot.funding.current } },
  now,
  DEFAULT_RISK_CONFIG,
);
if (!verdict.approved) {
  console.log(`governor vetoed: ${verdict.code} — ${verdict.reason}`);
  process.exit(0);
}

const apiKey = process.env.ANTHROPIC_API_KEY;
console.log(`\nrationale source: ${apiKey === undefined ? 'template (no ANTHROPIC_API_KEY)' : 'Claude'}`);

const result = await publishThenExecute(signal, {
  store,
  now,
  rationale: async (frozen) => {
    const r = await generateRationale(frozen, apiKey === undefined ? {} : { apiKey });
    console.log(`  → ${r.source}${r.fallbackReason === undefined ? '' : ` (${r.fallbackReason})`}`);
    return r.text;
  },
  execute: async (entry) => {
    console.log(`  executor received PUBLISHED entry seq=${entry.seq} hash=${entry.hash.slice(0, 16)}…`);
  },
});

console.log(`\n${'='.repeat(84)}\nWHAT A SUBSCRIBER RECEIVES\n${'='.repeat(84)}`);
console.log(formatSignalForDelivery(result.entry));

console.log(`\n${'='.repeat(84)}\nTHE FEED ENTRY (GET /signals/${result.entry.id})\n${'='.repeat(84)}`);
console.log(JSON.stringify(result.entry, null, 2));

// A couple of closed trades so the track record has something to compute from.
store.recordOutcome({
  signalId: result.entry.id,
  instId,
  side: signal.side,
  openedAt: now - 7_200_000,
  closedAt: now - 3_600_000,
  entryPrice: snapshot.last,
  exitPrice: snapshot.last * 0.995,
  contracts: verdict.sizing.contracts,
  netPnlUsdt: -3.94,
  rMultiple: -1,
  fundingUsdt: 0.02,
  reason: 'stop',
  equityAfter: 396.06,
});

console.log(`\n${'='.repeat(84)}\nGET /track-record\n${'='.repeat(84)}`);
console.log(JSON.stringify(buildTrackRecord(store, Date.now()), null, 2));

console.log(`\n${'='.repeat(84)}\nMCP TOOL: plumb_risk_disclosure\n${'='.repeat(84)}`);
console.log(JSON.stringify(callTool('plumb_risk_disclosure', {}, { store, now: () => Date.now() }).data, null, 2));

console.log(`\nchain verify: ${JSON.stringify(store.verifyChain())}`);
store.close();
